Add npm,release, native SDK version in README.md
ekreative/react-native-braintree pull request #80
Opened 2023-10-31 11:54 UTC by d982h8st7

#52 
## Update README.md with Native SDK Versions

This PR updates the README.md to display the native SDK versions for both Android and iOS. The table in the README now provides a clear overview of the NPM version, package version (based on release tags), Android SDK, and iOS SDK. 

- Android SDK: 28 (Based on `compileSdkVersion` in the `android/build.gradle` file)
- iOS SDK: 12.0 (Derived from the `IPHONEOS_DEPLOYMENT_TARGET` in the `project.pbxproj` file)

The table content and layout have been centered for better readability.

2023-10-31 16:17 UTC, vasylnahuliak commented on README.md
> +<!-- ALL-CONTRIBUTORS-LIST:END -->
Is this change needed?

2023-10-31 16:18 UTC, vasylnahuliak requested changes

2023-10-31 16:18 UTC, vasylnahuliak commented on README.md
> +<!-- ALL-CONTRIBUTORS-LIST:END -->
Is this change needed?

2023-10-31 19:06 UTC, merged

2023-11-01 00:31 UTC, ad-astra-per-ardua commented on README.md
> +<!-- ALL-CONTRIBUTORS-LIST:END -->
Isn't it just because 8 lines were added in front? @vasylnahuliak