Feature: Add userAction option to showPayPalModule
ekreative/react-native-braintree pull request #90
Opened 2024-08-02 18:14 UTC by short-dsb

Adds the ability to optionally pass a `userAction` of `"commit"` to the `showPayPalModule` method. The default behavior is unchanged.

* [Android documentation](https://braintree.github.io/braintree_android/PayPalNativeCheckout/com.braintreepayments.api/-pay-pal-native-checkout-request/index.html)
* [iOS documentation](https://braintree.github.io/braintree_ios/current/Classes/BTPayPalCheckoutRequest.html#/c:@M@BraintreePayPal@objc(cs)BTPayPalCheckoutRequest(py)userAction)

2024-08-12 14:54 UTC, vasylnahuliak requested changes

2024-08-12 14:54 UTC, vasylnahuliak commented on index.d.ts
> +  export interface PayPalOptions {
Could you create the `BaseOptions` interface?

[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2024-08-12 14:54 UTC, vasylnahuliak commented on index.d.ts
> +    userAction?: 'commit' | '';
The empty string it's strange. Could share some information about that approach?

2024-08-12 17:09 UTC, short-dsb commented on index.d.ts
> +  export interface PayPalOptions {
Good call.

2024-08-12 17:09 UTC, short-dsb commented on index.d.ts
> +    userAction?: 'commit' | '';
It’s oddly the default value, but we can definitely improve the JS ergonomics here.

2024-08-14 15:50 UTC, merged

2024-08-15 05:59 UTC, vasylnahuliak commented
Released in [v2.6.0](https://github.com/ekreative/react-native-braintree/releases/tag/v2.6.0)